[project]
name = "simple-neural-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.4",
]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
]
